name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: nvidia/cuda:12.2.0-devel-ubuntu22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools and linter
        run: |
          apt-get update
          apt-get install -y build-essential cmake git clang-tidy

      - name: Configure CMake project
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          make -j$(nproc)

      - name: Run clang-tidy on C++/CUDA files
        run: |
          find src -name '*.cpp' -o -name '*.cu' | xargs clang-tidy --quiet || true
